<?php
return [
'yijing' => [
    'name' => '周易',
    'brief' => '群经之首，卦象(伏羲)、 卦辞(文王)、爻辞(周公)、易传(孔子)。朱熹解易、王弼周易注、苏轼东坡易传。',
    'desc' => '周，代名也。易，書名也。其卦本伏羲所畫，有交易、變易之義，故謂之易。其辭則文王、周公所繫，故繫之周。以其簡袠重大，故分為上下兩篇。《經》則伏羲之畫，文王、周公之辭也。並孔子所作之《傳》十篇，凡十二篇。中間頗為諸儒所亂。近世晁氏始正其失，而未能盡合古文。呂氏又更定著為《經》二卷、《傳》十卷，乃復孔氏之舊云。',
    'tabs' => ['zhuxi', 'wangbi', 'sushi', 'yiwen', 'simple'],
],
'lunyu' => [
    'name' => '论语',
    'brief' => '记录孔子及其弟子言行而编成的语录文集，全书共20篇492章。',
    'desc' => '是春秋时期思想家、教育家孔子的弟子及再传弟子记录孔子及其弟子言行而编成的语录文集，成书于战国前期。全书共20篇492章，以语录体为主，叙事体为辅，较为集中地体现了孔子及儒家学派的政治主张、伦理思想、道德观念、教育原则等。作品多为语录，但辞约义富，有些语句、篇章形象生动，其主要特点是语言简练，浅近易懂，而用意深远，有一种雍容和顺、纡徐含蓄的风格，能在简单的对话和行动中展示人物形象。《论语》自宋代以后，被列为“四书”之一，成为古代学校官定教科书和科举考试必读书。',
    'tabs' => ['commentinner', 'zhuxi', 'yiwen'],
    'rowCount' => 4,
    'noteType' => 'inner',
    'rowCountMobile' => 4,
],
'daodejing' => [
    'name' => '道德经',
    'brief' => '道德经描述',
    'rowCount' => 5,
    'noteType' => 'inner',
    'rowCountMobile' => 4,
],
'daxue' => [
    'name' => '大学',
    'brief' => '大学描述',
    'noteType' => 'inner',
    'rowCount' => 4,
    'tabs' => ['commentinner', 'zhuxi', 'yiwen'],
    'rowCountMobile' => 2,
],
'zhongyong' => [
    'name' => '中庸',
    'brief' => '中庸描述',
    'rowCount' => 4,
    'tabs' => ['commentinner', 'zhuxi', 'yiwen'],
    'rowCountMobile' => 4,
    'noteType' => 'inner',
],
'mengzi' => [
    'name' => '孟子',
    'brief' => '孟子描述',
    //'rowspan' => 43,
    'onlyName' => true,
    'noteType' => 'inner',
    //'chapterList' => true,
    'tabs' => ['commentinner', 'zhuxi', 'yiwen'],
    'cUnit' => '段',
    'rowCount' => 2,
    'rowCountMobile' => 2,
],
'zhuangzi' => [
    'name' => '庄子',
    'brief' => '庄子描述',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'shangshu' => [
    'name' => '尚书',
    'brief' => '书经',
    'noteType' => 'inner',
    'rowCount' => 6,
    'rowCountMobile' => 5,
],
'shijing' => [
    'spell' => 1,
    'rowspan' => 15,
    'name' => '诗经',
    'brief' => '诗经',
    'rowCount' => 5,
    'rowCountMobile' => 3,
],
'xunzi' => [
    'name' => '荀子',
    'brief' => '荀子描述',
    'rowCount' => 5,
    'noteType' => 'inner',
    'rowCountMobile' => 3,
],
'mozi' => [
    'name' => '墨子',
    'brief' => '墨子描述',
    'rowCount' => 5,
    'noteType' => 'inner',
    'rowCountMobile' => 3,
],
'hanfeizi' => [
    'name' => '韩非子',
    'brief' => '韩非子',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'chunqiu' => [
    'name' => '春秋',
    'brief' => '春秋',
    'noteType' => 'inner',
    'rowCount' => 5,
    'rowCountMobile' => 4,
],
/*'gongyangzhuan' => [
    'name' => '公羊传',
    'brief' => '',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],*/
'zuozhuan' => [
    'name' => '左传',
    'brief' => '春秋左传',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'sunzibingfa' => [
    'name' => '孙子兵法',
    'brief' => '孙子兵法',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'liji' => [
    'name' => '礼记',
    'brief' => '礼记',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'chuanxilu' => [
    'name' => '传习录',
    'brief' => '传习录',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'chuci' => [
    'spell' => 1,
    'name' => '楚辞',
    'brief' => '诗经',
    'rowCount' => 5,
    'rowCountMobile' => 3,
],
'guwenguanzhi' => [
    //'rowspan' => 10,
    'name' => '古文观止',
    'withAuthor' => 1,
    'brief' => '古文观止',
    'noteType' => 'inner',
    'rowCount' => 2,
    'rowCountMobile' => 2,
],
'guwenguanzhishiyi' => [
    //'rowspan' => 10,
    'name' => '古文观止',
    'withTitle' => 1,
    'brief' => '古文观止',
    'noteType' => 'inner',
    'rowCount' => 2,
    'rowCountMobile' => 2,
],
'guoyu' => [
    'name' => '国语',
    'brief' => '国语',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 2,
],
'daxuegu' => [
    'name' => '大学(古本)',
    'brief' => '古本大学',
    'noteType' => 'inner',
    'rowCount' => 3,
    'rowCountMobile' => 3,
],
'yizhuan' => [
    'name' => '易传',
    'brief' => '易传',
    'rowCount' => 5,
    'rowCountMobile' => 3,
],
'xiaojing' => [
    'name' => '孝经',
    'brief' => '孝经',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'nvxiaojing' => [
    'name' => '女孝经',
    'brief' => '孝经',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'erya' => [
    'name' => '尔雅',
    'brief' => '尔雅',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 2,
],
'zhouli' => [
    'name' => '周礼',
    'brief' => '周礼',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'yili' => [
    'name' => '仪礼',
    'brief' => '仪礼',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'daliji' => [
    'name' => '大戴礼记',
    'brief' => '大戴礼记',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
'shanhaijing' => [
    'name' => '山海经',
    'brief' => '山海经',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'sushu' => [
    'name' => '素书',
    'brief' => '素书',
    //'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'qianziwen' => [
    'name' => '千字文',
    'brief' => '千字文',
    'spell' => 1,
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'sanshiliuji' => [
    'name' => '三十六计',
    'brief' => '三十六计',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'sanzijing' => [
    'name' => '三字经',
    'brief' => '三字经',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'caigentan' => [
    'name' => '菜根谭',
    'brief' => '菜根谭',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 3,
],
'zhushu' => [
    'name' => '竹书纪年',
    'brief' => '竹书纪年',
    'noteType' => 'inner',
    'rowCount' => 4,
    'rowCountMobile' => 4,
],
];
